loggingDir: log
dataConfig:
  cmdIdPath: data/Sorapointa-Protos/cmdid.csv
  protoPath: data/Sorapointa-Protos/proto
  outputPath: data/output
  dispatchRegion: # fill in your dispatchRegion
  privateKeyPath: data/private_key_5.pem
device: # fill in your network interface name
seed: # fill in your seed, if you want to continue from a previous session
